Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/03/2022
Var

n1:inteiro
Inicio
      Escreva("Digite um número ")
      leia(n1)

      se n1%2 = 0 entao
         n1<- n1 +5
      senao
       n1 <- n1 +8
      fimse
      escreva(n1)
Fimalgoritmo