Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/03/2022
Var

   N1: inteiro

Inicio
      Escreva("Digite um valor [Inteiro]: ")
      leia(n1)
      
      SE n1%2= 0  entao
         escreva("O número ",n1," é PAR!")
      SENAO
         escreva("O número ",n1," é ÍMPAR!")
      FIMSE
Fimalgoritmo